image: Visual Studio 2019
configuration: Release

environment:
  matrix:
    - CFLAGS: /WX
      CXXFLAGS: /WX

install:
 - mkdir build && cd build
 - cmake .. -G "Visual Studio 16 2019" -A x64

build:
  project: darktable.sln

artifacts:
  - path: bin\**\*darktable*.exe
